name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:8
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        working-directory: ./scalafix
        run: sbt test